# Created by: Vladimir Vinogradenko <vladimirv@ixsystems.com
# $FreeBSD$

PORTNAME=	onedrivesdk
PORTVERSION=	1.1.8
CATEGORIES=	truenas devel python
VALID_CATEGORIES+= truenas
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Official Python OneDrive SDK for interfacing with OneDrive APIs

# OneDrive/onedrive-sdk-python
LICENSE=	MIT

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
