"""Simplify SMB shares

Revision ID: bc290fddc888
Revises: 536cbfca20e6
Create Date: 2020-01-16 19:16:53.973957+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc290fddc888'
down_revision = '536cbfca20e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Move VFS objects into new boolean values. If users have a non-standard
    set, append them as auxilary parameters to the SMB share to preseve
    existing configuration. Same for other columns that are being dropped.
    This will preserve existing share behavior post-migration.
    """
    standard_vfs_objects = ['ixnas', 'streams_xattr', 'fruit', 'catia']
    # Модули VFS, которых в стоковой Samba нет: их поставляла только
    # сборка iXsystems. Утащить такой модуль в auxsmbconf — значит
    # получить шару, которую smbd не может открыть: в логе
    # "error probing vfs module 'zfs_space'", а клиент видит
    # NT_STATUS_BAD_NETWORK_NAME. У FreeNAS 9.x список по умолчанию был
    # zfs_space,zfsacl,streams_xattr, то есть под это попадала КАЖДАЯ
    # шара. Выкидываем их из переносимого списка: потеря — отчёт о
    # свободном месте по датасету вместо пула, приобретение — рабочая шара.
    ix_only_vfs_objects = ['zfs_space', 'ixnas']
    fruit_enabled = False
    has_acl = True
    has_streams =False
    has_catia = False
    set_durable = True
    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cifs_srv_aapl_extensions', sa.Boolean(), nullable=True))
        batch_op.drop_column('cifs_srv_aio_enable')
        batch_op.drop_column('cifs_srv_aio_rs')
        batch_op.drop_column('cifs_srv_aio_ws')

    with op.batch_alter_table('sharing_cifs_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cifs_purpose', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cifs_acl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cifs_aapl_name_mangling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cifs_path_suffix', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cifs_streams', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cifs_durablehandle', sa.Boolean(), nullable=True))

    conn = op.get_bind()
    smb_shares = [dict(row) for row in conn.execute("SELECT * FROM sharing_cifs_share").fetchall()]
    for share in smb_shares:
        aux_params = share.get('cifs_auxsmbconf', '').split('\n')
        vfs_objects = share.get('cifs_vfsobjects', '')
        has_nondefault_vfs_objects = False
        aux_updated = False

        for v in vfs_objects.split(','):
            if v in ix_only_vfs_objects:
                continue
            if v not in standard_vfs_objects:
                set_durable = False
                has_nondefault_vfs_objects = True

            if v == 'fruit':
                fruit_enabled = True
            if v == 'streams_xattr':
                has_streams = True
            if v == 'noacl':
                has_acl = False
            if v == 'catia':
                has_catia = True

        if share['cifs_timemachine']:
            fruit_enabled = True

        if share['cifs_showhiddenfiles']:
            aux_params.append('hide dot files = no')

        if share['cifs_guestonly']:
            aux_params.append('guest only = yes')

        if has_nondefault_vfs_objects:
            kept = [v for v in vfs_objects.split(',')
                    if v and v not in ix_only_vfs_objects]
            if kept:
                aux_params.append(f"vfs objects = {' '.join(kept)}")

        new_aux = '\n'.join(aux_params)
        conn.execute("UPDATE sharing_cifs_share SET cifs_acl = :acl, cifs_streams = :streams, "
                     "cifs_aapl_name_mangling = :catia, cifs_durablehandle= :durable, "
                     "cifs_path_suffix = '', cifs_auxsmbconf = :aux, cifs_purpose = 'NO_PRESET' "
                     "WHERE id=:share_id", acl=has_acl, streams=has_streams, catia=has_catia,
                     durable=set_durable, aux=new_aux, share_id=share['id'])

    op.execute(f"UPDATE services_cifs SET cifs_srv_aapl_extensions = {fruit_enabled}")

    with op.batch_alter_table('sharing_cifs_share', schema=None) as batch_op:
        batch_op.drop_column('cifs_vfsobjects')
        batch_op.drop_column('cifs_showhiddenfiles')
        batch_op.drop_column('cifs_guestonly')

    with op.batch_alter_table('sharing_cifs_share', schema=None) as batch_op:
        batch_op.alter_column('cifs_purpose', nullable=False)
        batch_op.alter_column('cifs_acl', nullable=False)
        batch_op.alter_column('cifs_streams', nullable=False)
        batch_op.alter_column('cifs_path_suffix', nullable=False)
        batch_op.alter_column('cifs_aapl_name_mangling', nullable=False)
        batch_op.alter_column('cifs_durablehandle', nullable=False)

    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.alter_column('cifs_srv_aapl_extensions', nullable=False)

    # ### end Alembic commands ###
